# Generated by Django 4.1.2 on 2022-11-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blogs",
            new_name="All_Blogs",
        ),
    ]
